---
- hosts: servers

  roles:
    - role: disable-selinux
      when: ansible_distribution  == 'CentOS'

    - role: install-pkgs-co7
      when: ansible_distribution  == 'CentOS' and
            ansible_distribution_major_version == '7'

    - role: install-pkgs-u2004
      when: ansible_distribution  == 'Ubuntu' and
            ansible_distribution_version == '20.04'

    - role: set-hostname

    - role: set-timezone

    - role: set-timesyncd
      when: ansible_distribution  == 'Ubuntu'

    - role: set-ntp
      when: ansible_distribution  == 'CentOS'

    - role: remove-snapd
      when: ansible_distribution  == 'Ubuntu' and
            ansible_distribution_version == '20.04'

    - role: remove-cloud-init
      when: ansible_distribution  == 'Ubuntu' and
            ansible_distribution_version == '20.04'

    - role: mute-bell

    - role: set-bashrc

    - role: set-vimrc

    - role: disable-cron-mail

    - role: set-profile

    - role: opt-sysctl

    - role: set-bbr
      when: ansible_distribution  == 'Ubuntu'

    - role: set-ipv6

    - role: opt-limits

  tasks:
    - debug:
        msg: 
          - 'Moss Has Configured System Successfully!'
          - 'Please Reboot Host!'
