- name: 'Install Packages for Debian 11'
  tags: 'install-pkgs-debian11'
  apt:
    name: "{{ PKGS }}"
    state: present
    update_cache: yes
  register: task_output
  when: ansible_distribution  == 'Debian' and 
        ansible_distribution_version == '11'

- debug: var=task_output.stdout_lines
