- name: 'Install ntpdate Package'
  tags: 'set-ntpdate'
  package:
    name: ntpdate
    state: present

- name: 'Perform a Time Sync'
  tags: 'set-ntpdate'
  shell:
    cmd: 'ntpdate {{ NTP_SERVER }}'

- name: 'Create ntpdate cron Job'
  tags: 'set-ntpdate'
  cron:
    name: 'Time Sync'
    user: root
    state: present
    minute: '0'
    hour: '*/3'
    job: 'ntpdate {{ NTP_SERVER }} && hwclock -w > /dev/null 2>&1'
