- name: 'Optimize System Limits Config File'
  tags: 'opt-limits'
  template:
    src: '100-moss.conf.template'
    dest: '/etc/security/limits.d/100-moss.conf'
    mode: 0644

- name: 'Optimize Systemd Limits'
  tags: 'opt-limits'
  lineinfile:
    dest: '/etc/systemd/system.conf'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { 'regexp':'^#?DefaultLimitCORE=', 'line':'DefaultLimitCORE=100000' }
    - { 'regexp':'^#?DefaultLimitNOFILE=', 'line':'DefaultLimitNOFILE=100000' }
  when: not (ansible_distribution  == 'CentOS' and
        ansible_distribution_major_version == '6')
