- name: 'Enable root SSH Login'
  tags: 'root-ssh'
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin yes'
    state: present
  notify:
    - 'Restart sshd Service'

- name: 'Disable SSH DNS Reverse Resolve'
  tags: 'root-ssh'
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^#?UseDNS'
    line: 'UseDNS no'
    state: present
  notify:
    - 'Restart sshd Service'
  when: ansible_distribution  == 'CentOS'
